image: python:3.6-slim-stretch

stages:
  - deploy

deploy to pypi:
  stage: deploy
  when: manual
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v[0-9]+[.][0-9]+[.][0-9]+([.][^.]+)?$/
  before_script:
    - pip install --no-cache-dir twine
  script:
    - sed -i "s/@@VERSION@@/$CI_COMMIT_TAG/g" ./setup.py
    - python setup.py sdist
    - python setup.py bdist_wheel
    - twine upload -r pypi -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
